---
title: "House of Representatives - Primary Vote"
author: "Carlos YANEZ SANTIBANEZ"
date: "2022-11-11"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{House of Representatives - Primary Vote}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



**auspol** includes two functions to interact with the preference distribution data:

- get_house_primary_vote()
- house_primary_vote_summary()
- house_primary_comparison_plot()
- house_primary_historic_plot()

## What is this?

If you are unfamiliar with the Australian electoral system and preferential voting, please look at this [explainer(https://www.aec.gov.au/learn/preferential-voting.html) before proceeding.


## Getting the data

*get_house_primary_vote()* is the basic function to retrieve primary vote data as published by the AEC. Without any arguments, it will delivery all the results for all elections, but it comes with parameters to facilitate filtering.
For instance, to get the results for Brisbane for 2022:


```r
get_house_primary_vote(division="Brisbane",year=2022)
#> # A tibble: 344 × 17
#>     Year StateAb DivisionID DivisionNm Pollin…¹ Polli…² Candi…³ Surname GivenNm Ballo…⁴ Elected Histo…⁵ PartyAb PartyNm Ordin…⁶ Swing
#>    <dbl> <chr>        <int> <chr>         <int> <chr>     <int> <chr>   <chr>     <int> <lgl>   <lgl>   <chr>   <chr>     <int> <dbl>
#>  1  2022 QLD            156 Brisbane      83397 Alderl…   37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      23  2.31
#>  2  2022 QLD            156 Brisbane      83397 Alderl…   35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      25  0.77
#>  3  2022 QLD            156 Brisbane      83397 Alderl…   37338 BATES   Stephen       3 TRUE    FALSE   GRN     Queens…     251  3.43
#>  4  2022 QLD            156 Brisbane      83397 Alderl…   37230 JARRETT Madonna       4 FALSE   FALSE   ALP     Austra…     315  1.27
#>  5  2022 QLD            156 Brisbane      83397 Alderl…   37482 EVANS   Trevor        5 FALSE   TRUE    LNP     Libera…     328 -9.97
#>  6  2022 QLD            156 Brisbane      83397 Alderl…   38213 HOLD    Trevor        6 FALSE   FALSE   ON      Paulin…      31  1.5 
#>  7  2022 QLD            156 Brisbane      83397 Alderl…   37311 BULL    Anthony       7 FALSE   FALSE   LDP     Libera…      22  2.21
#>  8  2022 QLD            156 Brisbane      83397 Alderl…     999 Inform… Inform…     999 FALSE   FALSE   Inform… Inform…      20 -1.17
#>  9  2022 QLD            156 Brisbane       6017 Ascot     37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      35  1.65
#> 10  2022 QLD            156 Brisbane       6017 Ascot     35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      62  2.06
#> # … with 334 more rows, 1 more variable: SittingMemberFl <lgl>, and abbreviated variable names ¹​PollingPlaceID, ²​PollingPlace,
#> #   ³​CandidateID, ⁴​BallotPosition, ⁵​HistoricElected, ⁶​OrdinaryVotes
```

Both parameters can include more than one value, e.g.


```r
get_house_primary_vote(division="Brisbane",year=c(2019,2022))
#> # A tibble: 712 × 17
#>     Year StateAb DivisionID DivisionNm Pollin…¹ Polli…² Candi…³ Surname GivenNm Ballo…⁴ Elected Histo…⁵ PartyAb PartyNm Ordin…⁶ Swing
#>    <dbl> <chr>        <int> <chr>         <int> <chr>     <int> <chr>   <chr>     <int> <lgl>   <lgl>   <chr>   <chr>     <int> <dbl>
#>  1  2022 QLD            156 Brisbane      83397 Alderl…   37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      23  2.31
#>  2  2022 QLD            156 Brisbane      83397 Alderl…   35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      25  0.77
#>  3  2022 QLD            156 Brisbane      83397 Alderl…   37338 BATES   Stephen       3 TRUE    FALSE   GRN     Queens…     251  3.43
#>  4  2022 QLD            156 Brisbane      83397 Alderl…   37230 JARRETT Madonna       4 FALSE   FALSE   ALP     Austra…     315  1.27
#>  5  2022 QLD            156 Brisbane      83397 Alderl…   37482 EVANS   Trevor        5 FALSE   TRUE    LNP     Libera…     328 -9.97
#>  6  2022 QLD            156 Brisbane      83397 Alderl…   38213 HOLD    Trevor        6 FALSE   FALSE   ON      Paulin…      31  1.5 
#>  7  2022 QLD            156 Brisbane      83397 Alderl…   37311 BULL    Anthony       7 FALSE   FALSE   LDP     Libera…      22  2.21
#>  8  2022 QLD            156 Brisbane      83397 Alderl…     999 Inform… Inform…     999 FALSE   FALSE   Inform… Inform…      20 -1.17
#>  9  2022 QLD            156 Brisbane       6017 Ascot     37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      35  1.65
#> 10  2022 QLD            156 Brisbane       6017 Ascot     35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      62  2.06
#> # … with 702 more rows, 1 more variable: SittingMemberFl <lgl>, and abbreviated variable names ¹​PollingPlaceID, ²​PollingPlace,
#> #   ³​CandidateID, ⁴​BallotPosition, ⁵​HistoricElected, ⁶​OrdinaryVotes
```


```r
get_house_primary_vote(division=c("Brisbane","Perth"),year=c(2019,2022))
#> # A tibble: 1,783 × 17
#>     Year StateAb DivisionID DivisionNm Pollin…¹ Polli…² Candi…³ Surname GivenNm Ballo…⁴ Elected Histo…⁵ PartyAb PartyNm Ordin…⁶ Swing
#>    <dbl> <chr>        <int> <chr>         <int> <chr>     <int> <chr>   <chr>     <int> <lgl>   <lgl>   <chr>   <chr>     <int> <dbl>
#>  1  2022 QLD            156 Brisbane      83397 Alderl…   37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      23  2.31
#>  2  2022 QLD            156 Brisbane      83397 Alderl…   35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      25  0.77
#>  3  2022 QLD            156 Brisbane      83397 Alderl…   37338 BATES   Stephen       3 TRUE    FALSE   GRN     Queens…     251  3.43
#>  4  2022 QLD            156 Brisbane      83397 Alderl…   37230 JARRETT Madonna       4 FALSE   FALSE   ALP     Austra…     315  1.27
#>  5  2022 QLD            156 Brisbane      83397 Alderl…   37482 EVANS   Trevor        5 FALSE   TRUE    LNP     Libera…     328 -9.97
#>  6  2022 QLD            156 Brisbane      83397 Alderl…   38213 HOLD    Trevor        6 FALSE   FALSE   ON      Paulin…      31  1.5 
#>  7  2022 QLD            156 Brisbane      83397 Alderl…   37311 BULL    Anthony       7 FALSE   FALSE   LDP     Libera…      22  2.21
#>  8  2022 QLD            156 Brisbane      83397 Alderl…     999 Inform… Inform…     999 FALSE   FALSE   Inform… Inform…      20 -1.17
#>  9  2022 QLD            156 Brisbane       6017 Ascot     37204 KENNEDY Tiana         1 FALSE   FALSE   AJP     Animal…      35  1.65
#> 10  2022 QLD            156 Brisbane       6017 Ascot     35972 KNUDSON Justin…       2 FALSE   FALSE   UAPP    United…      62  2.06
#> # … with 1,773 more rows, 1 more variable: SittingMemberFl <lgl>, and abbreviated variable names ¹​PollingPlaceID, ²​PollingPlace,
#> #   ³​CandidateID, ⁴​BallotPosition, ⁵​HistoricElected, ⁶​OrdinaryVotes
```

By default, the results are presented by polling place, with it is possible to aggregate them.


```r
get_house_primary_vote(division=c("Brisbane","Perth"),year=c(2019,2022),aggregation = TRUE)
#> # A tibble: 37 × 14
#>     Year StateAb DivisionID DivisionNm CandidateID Surname   GivenNm  BallotPosition Elected Histor…¹ PartyAb PartyNm Sitti…² Ordin…³
#>    <dbl> <chr>        <int> <chr>            <int> <chr>     <chr>             <int> <lgl>   <lgl>    <chr>   <chr>   <lgl>     <int>
#>  1  2019 QLD            156 Brisbane           999 Informal  Informal            999 FALSE   FALSE    Inform… Inform… FALSE      1999
#>  2  2019 QLD            156 Brisbane         32751 PERRY     Anne                  1 FALSE   FALSE    ON      Paulin… FALSE      1641
#>  3  2019 QLD            156 Brisbane         32946 NEWBURY   Paul                  6 FALSE   FALSE    ALP     Austra… FALSE     19018
#>  4  2019 QLD            156 Brisbane         32960 WHITTAKER Aaron                 3 FALSE   FALSE    UAPP    United… FALSE       975
#>  5  2019 QLD            156 Brisbane         33144 BARTLETT  Andrew                4 FALSE   FALSE    GRN     The Gr… FALSE     17247
#>  6  2019 QLD            156 Brisbane         33206 EVANS     Trevor                2 TRUE    TRUE     LNP     Libera… FALSE     36119
#>  7  2019 QLD            156 Brisbane         33224 EMANUEL   Kamala                7 FALSE   FALSE    SAL     Social… FALSE       528
#>  8  2019 QLD            156 Brisbane         33326 JEANNERET Rod                   5 FALSE   FALSE    FACN    FRASER… FALSE       526
#>  9  2019 WA             245 Perth              999 Informal  Informal            999 FALSE   FALSE    Inform… Inform… FALSE      3548
#> 10  2019 WA             245 Perth            32155 PERKS     Caroline              6 FALSE   FALSE    GRN     The Gr… FALSE     13234
#> # … with 27 more rows, and abbreviated variable names ¹​HistoricElected, ²​SittingMemberFl, ³​OrdinaryVotes
```



```r
get_house_primary_vote(division=c("Brisbane","Perth"),year=c(2019,2022), polling_places = c("Yokine North"))
#> # A tibble: 12 × 17
#>     Year StateAb DivisionID DivisionNm Polli…¹ Polli…² Candi…³ Surname GivenNm Ballo…⁴ Elected Histo…⁵ PartyAb PartyNm Ordin…⁶  Swing
#>    <dbl> <chr>        <int> <chr>        <int> <chr>     <int> <chr>   <chr>     <int> <lgl>   <lgl>   <chr>   <chr>     <int>  <dbl>
#>  1  2022 WA             245 Perth         8203 Yokine…   37417 BAILEY  Cameron       1 FALSE   FALSE   ON      Paulin…      25  -0.97
#>  2  2022 WA             245 Perth         8203 Yokine…   36515 POWELL  Dean          2 FALSE   FALSE   AUC     Austra…      18   0.2 
#>  3  2022 WA             245 Perth         8203 Yokine…   37748 CONNOR  Sean          3 FALSE   FALSE   GAP     The Gr…      14   1.54
#>  4  2022 WA             245 Perth         8203 Yokine…   37803 VOS     Dave          4 FALSE   FALSE   WAP     WESTER…      18  -0.19
#>  5  2022 WA             245 Perth         8203 Yokine…   37233 SZMEKU… Sarah         5 FALSE   FALSE   AJP     Animal…      14   1.54
#>  6  2022 WA             245 Perth         8203 Yokine…   37327 GORMAN  Patrick       6 TRUE    TRUE    ALP     Austra…     341   7.73
#>  7  2022 WA             245 Perth         8203 Yokine…   37273 NICKOLS Evan          7 FALSE   FALSE   LDP     Libera…      18   1.98
#>  8  2022 WA             245 Perth         8203 Yokine…   36507 EBERHA… Sonya …       8 FALSE   FALSE   UAPP    United…      23   1.21
#>  9  2022 WA             245 Perth         8203 Yokine…   36628 PERKS   Caroli…       9 FALSE   FALSE   GRN     The Gr…     138   2.23
#> 10  2022 WA             245 Perth         8203 Yokine…   36601 DWYER   David        10 FALSE   FALSE   LP      Liberal     298 -15.7 
#> 11  2022 WA             245 Perth         8203 Yokine…   37290 GYURU   Aiden        11 FALSE   FALSE   CYA     Austra…       4   0.44
#> 12  2022 WA             245 Perth         8203 Yokine…     999 Inform… Inform…     999 FALSE   FALSE   Inform… Inform…      80   2.8 
#> # … with 1 more variable: SittingMemberFl <lgl>, and abbreviated variable names ¹​PollingPlaceID, ²​PollingPlace, ³​CandidateID,
#> #   ⁴​BallotPosition, ⁵​HistoricElected, ⁶​OrdinaryVotes
```

It is also possible to restrict the results to selected polling places



Additionally, it is possible to select one or more states instead of a group divisions, e.g.:


```r
get_house_primary_vote(state=c("TAS"),year=c(2019,2022),aggregation = TRUE)
#> # A tibble: 86 × 14
#>     Year StateAb DivisionID DivisionNm CandidateID Surname  GivenNm    BallotPosition Elected Histo…¹ PartyAb PartyNm Sitti…² Ordin…³
#>    <dbl> <chr>        <int> <chr>            <int> <chr>    <chr>               <int> <lgl>   <lgl>   <chr>   <chr>   <lgl>     <int>
#>  1  2019 TAS            192 Bass               999 Informal Informal              999 FALSE   FALSE   Inform… Inform… FALSE      2962
#>  2  2019 TAS            192 Bass             32124 ARCHER   Bridget                 4 TRUE    FALSE   LP      Liberal FALSE     25401
#>  3  2019 TAS            192 Bass             32327 HART     Ross                    2 FALSE   TRUE    ALP     Austra… FALSE     20882
#>  4  2019 TAS            192 Bass             32379 WOODBURY Susan                   3 FALSE   FALSE   AJP     Animal… FALSE      1422
#>  5  2019 TAS            192 Bass             32399 COOPER   Carl                    7 FALSE   FALSE   NP      The Na… FALSE       783
#>  6  2019 TAS            192 Bass             32540 HALL     Tom                     1 FALSE   FALSE   GRN     The Gr… FALSE      6198
#>  7  2019 TAS            192 Bass             32545 ROARK    Allan John              6 FALSE   FALSE   UAPP    United… FALSE      2891
#>  8  2019 TAS            192 Bass             33590 LAMBERT  Todd                    5 FALSE   FALSE   IND     Indepe… FALSE      2229
#>  9  2019 TAS            193 Braddon            999 Informal Informal              999 FALSE   FALSE   Inform… Inform… FALSE      5023
#> 10  2019 TAS            193 Braddon          32094 BRAKEY   Craig                   2 FALSE   FALSE   IND     Indepe… FALSE      7046
#> # … with 76 more rows, and abbreviated variable names ¹​HistoricElected, ²​SittingMemberFl, ³​OrdinaryVotes
```

It is also possible to filter results by one or more parties:


```r
get_house_primary_vote(state=c("NT"),year=c(2019,2022),aggregation = TRUE, party_abb=c("ALP","CLP"))
#> # A tibble: 8 × 14
#>    Year StateAb DivisionID DivisionNm CandidateID Surname    GivenNm   BallotPosition Elected Histo…¹ PartyAb PartyNm Sitti…² Ordin…³
#>   <dbl> <chr>        <int> <chr>            <int> <chr>      <chr>              <int> <lgl>   <lgl>   <chr>   <chr>   <lgl>     <int>
#> 1  2019 NT             306 Lingiari         32740 SNOWDON    Warren                 1 TRUE    TRUE    ALP     Austra… FALSE     20125
#> 2  2019 NT             306 Lingiari         33045 PRICE      Jacinta                6 FALSE   FALSE   CLP     Countr… FALSE     15918
#> 3  2019 NT             307 Solomon          32743 GOSLING    Luke John              1 TRUE    TRUE    ALP     Austra… FALSE     19484
#> 4  2019 NT             307 Solomon          33053 GANLEY     Kathy                  3 FALSE   FALSE   CLP     Countr… FALSE     18297
#> 5  2022 NT             306 Lingiari         36968 RYAN       Damien                 1 FALSE   FALSE   CLP     NT CLP  FALSE     13974
#> 6  2022 NT             306 Lingiari         37286 SCRYMGOUR  Marion                 5 TRUE    FALSE   ALP     A.L.P.  FALSE     15367
#> 7  2022 NT             307 Solomon          36937 MACFARLANE Tina                   4 FALSE   FALSE   CLP     NT CLP  FALSE     11989
#> 8  2022 NT             307 Solomon          37280 GOSLING    Luke                   3 TRUE    TRUE    ALP     A.L.P.  FALSE     18891
#> # … with abbreviated variable names ¹​HistoricElected, ²​SittingMemberFl, ³​OrdinaryVotes
```


*house_primary_vote_summary()* builds on the basic function and summarise data.

```r
house_primary_vote_summary(division = "Brisbane", year=2022)
#> # A tibble: 8 × 11
#>    Year StateAb DivisionNm GivenNm     Surname  PartyAb  PartyNm                              OrdinaryVotes Percent…¹ Perce…² Elected
#>   <dbl> <chr>   <chr>      <chr>       <chr>    <chr>    <chr>                                        <int>     <dbl>   <dbl> <lgl>  
#> 1  2022 QLD     Brisbane   Informal    Informal Informal Informal                                      1566      2.09    2.13 FALSE  
#> 2  2022 QLD     Brisbane   Justin Marc KNUDSON  UAPP     United Australia Party                        1430      1.91    1.95 FALSE  
#> 3  2022 QLD     Brisbane   Tiana       KENNEDY  AJP      Animal Justice Party                          1235      1.65    1.68 FALSE  
#> 4  2022 QLD     Brisbane   Madonna     JARRETT  ALP      Australian Labor Party                       20346     27.1    27.7  FALSE  
#> 5  2022 QLD     Brisbane   Anthony     BULL     LDP      Liberal Democrats                             1115      1.49    1.52 FALSE  
#> 6  2022 QLD     Brisbane   Stephen     BATES    GRN      Queensland Greens                            20985     28.0    28.6  TRUE   
#> 7  2022 QLD     Brisbane   Trevor      EVANS    LNP      Liberal National Party of Queensland         26801     35.7    36.5  FALSE  
#> 8  2022 QLD     Brisbane   Trevor      HOLD     ON       Pauline Hanson's One Nation                   1518      2.02    2.07 FALSE  
#> # … with abbreviated variable names ¹​Percentage_with_Informal, ²​Percentage
```

Using the previous filters,  it is possible to get ad-hoc summaries, for instance - all the ALP vote in Queensland in 2022, or the historic Liberal vote in Franklin.


```r

house_primary_vote_summary(state = "QLD", year=2022,parties="ALP")
#> # A tibble: 30 × 11
#>     Year StateAb DivisionNm  GivenNm Surname    PartyAb PartyNm                OrdinaryVotes Percentage_with_Informal Perce…¹ Elected
#>    <dbl> <chr>   <chr>       <chr>   <chr>      <chr>   <chr>                          <int>                    <dbl>   <dbl> <lgl>  
#>  1  2022 QLD     Bowman      Donisha DUFF       ALP     Australian Labor Party         23196                     28.7    29.6 FALSE  
#>  2  2022 QLD     Brisbane    Madonna JARRETT    ALP     Australian Labor Party         20346                     27.1    27.7 FALSE  
#>  3  2022 QLD     Capricornia Russell ROBERTSON  ALP     Australian Labor Party         20543                     26.9    28.7 FALSE  
#>  4  2022 QLD     Dawson      Shane   HAMILTON   ALP     Australian Labor Party         18921                     23.8    24.9 FALSE  
#>  5  2022 QLD     Fadden      Letitia DEL FABBRO ALP     Australian Labor Party         18140                     21.7    22.8 FALSE  
#>  6  2022 QLD     Fairfax     Sue     FERGUSON   ALP     Australian Labor Party         18001                     21.0    22.3 FALSE  
#>  7  2022 QLD     Fisher      Judene  ANDREWS    ALP     Australian Labor Party         19804                     22.9    23.7 FALSE  
#>  8  2022 QLD     Forde       Rowan   HOLZBERGER ALP     Australian Labor Party         18969                     26.1    28.2 FALSE  
#>  9  2022 QLD     Griffith    Terri   BUTLER     ALP     Australian Labor Party         21961                     27.9    28.4 FALSE  
#> 10  2022 QLD     Groom       Gen     ALLPASS    ALP     Australian Labor Party         13822                     18.3    19.4 FALSE  
#> # … with 20 more rows, and abbreviated variable name ¹​Percentage
```




```r
house_primary_vote_summary(division="Franklin",parties="LP")
#> # A tibble: 7 × 11
#>    Year StateAb DivisionNm GivenNm      Surname PartyAb PartyNm OrdinaryVotes Percentage_with_Informal Percentage Elected
#>   <dbl> <chr>   <chr>      <chr>        <chr>   <chr>   <chr>           <int>                    <dbl>      <dbl> <lgl>  
#> 1  2004 TAS     Franklin   Henry        FINNIS  LP      Liberal         21337                     37.6       39.0 FALSE  
#> 2  2007 TAS     Franklin   Vanessa      GOODWIN LP      Liberal         22616                     39.8       41.0 FALSE  
#> 3  2010 TAS     Franklin   Jane         HOWLETT LP      Liberal         18386                     32.0       33.3 FALSE  
#> 4  2013 TAS     Franklin   Bernadette   BLACK   LP      Liberal         21867                     37.1       38.7 FALSE  
#> 5  2016 TAS     Franklin   Amanda-Sue   MARKHAM LP      Liberal         20754                     33.9       35.1 FALSE  
#> 6  2019 TAS     Franklin   Dean         YOUNG   LP      Liberal         18591                     29.9       30.9 FALSE  
#> 7  2022 TAS     Franklin   Kristy Maree JOHNSON LP      Liberal         14374                     24.5       25.9 FALSE
```




## Plotting 

